"use client"

import { createContext, useContext, useState, useCallback, ReactNode } from 'react'

type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'es' | 'fr' | 'de' | 'ar'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  languages: { code: Language; name: string; nativeName: string }[]
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    myApplications: 'My Applications',
    schemes: 'Schemes',
    transparency: 'Transparency',
    help: 'Help',
    welcome: 'Welcome to Citizen Portal',
    welcomeDesc: 'Apply for subsidies and track your applications',
    applyNow: 'Apply Now',
    trackStatus: 'Track Status',
    viewAll: 'View All',
    submitted: 'Submitted',
    fraudCheck: 'Fraud Check',
    approved: 'Approved',
    disbursed: 'Disbursed',
    pending: 'Pending',
    rejected: 'Rejected',
    inProgress: 'In Progress',
    completed: 'Completed',
    expectedDate: 'Expected Date',
    amount: 'Amount',
    status: 'Status',
    schemeName: 'Scheme Name',
    education: 'Education',
    finance: 'Finance',
    agriculture: 'Agriculture',
    health: 'Health',
    housing: 'Housing',
    employment: 'Employment',
    eligibilityCheck: 'Check Eligibility',
    chatWithUs: 'Chat with Us',
    voiceAssistant: 'Voice Assistant',
    speakNow: 'Speak Now',
    listening: 'Listening...',
    recommendations: 'Recommended for You',
    totalApplications: 'Total Applications',
    approvedApplications: 'Approved',
    pendingApplications: 'Pending',
    disbursedAmount: 'Disbursed Amount',
    transparencyMetrics: 'Transparency Metrics',
    processingTime: 'Avg. Processing Time',
    successRate: 'Success Rate',
    totalDisbursed: 'Total Disbursed',
    askQuestion: 'Ask a question...',
    send: 'Send',
    close: 'Close',
    language: 'Language',
    profile: 'Profile',
    logout: 'Logout',
    notifications: 'Notifications',
    applicationTimeline: 'Application Timeline',
    viewDetails: 'View Details',
    applyForScheme: 'Apply for Scheme',
    checkEligibility: 'Check Eligibility',
    documentsRequired: 'Documents Required',
    benefits: 'Benefits',
    days: 'days',
    allSchemes: 'All Schemes',
    searchSchemes: 'Search schemes...',
    filterByCategory: 'Filter by category',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    myApplications: 'मेरे आवेदन',
    schemes: 'योजनाएं',
    transparency: 'पारदर्शिता',
    help: 'सहायता',
    welcome: 'नागरिक पोर्टल में आपका स्वागत है',
    welcomeDesc: 'सब्सिडी के लिए आवेदन करें और अपने आवेदनों को ट्रैक करें',
    applyNow: 'अभी आवेदन करें',
    trackStatus: 'स्थिति ट्रैक करें',
    viewAll: 'सभी देखें',
    submitted: 'जमा किया गया',
    fraudCheck: 'धोखाधड़ी जांच',
    approved: 'स्वीकृत',
    disbursed: 'वितरित',
    pending: 'लंबित',
    rejected: 'अस्वीकृत',
    inProgress: 'प्रगति में',
    completed: 'पूर्ण',
    expectedDate: 'अपेक्षित तिथि',
    amount: 'राशि',
    status: 'स्थिति',
    schemeName: 'योजना का नाम',
    education: 'शिक्षा',
    finance: 'वित्त',
    agriculture: 'कृषि',
    health: 'स्वास्थ्य',
    housing: 'आवास',
    employment: 'रोजगार',
    eligibilityCheck: 'पात्रता जांचें',
    chatWithUs: 'हमसे चैट करें',
    voiceAssistant: 'वॉइस असिस्टेंट',
    speakNow: 'अभी बोलें',
    listening: 'सुन रहा है...',
    recommendations: 'आपके लिए अनुशंसित',
    totalApplications: 'कुल आवेदन',
    approvedApplications: 'स्वीकृत',
    pendingApplications: 'लंबित',
    disbursedAmount: 'वितरित राशि',
    transparencyMetrics: 'पारदर्शिता मेट्रिक्स',
    processingTime: 'औसत प्रोसेसिंग समय',
    successRate: 'सफलता दर',
    totalDisbursed: 'कुल वितरित',
    askQuestion: 'एक प्रश्न पूछें...',
    send: 'भेजें',
    close: 'बंद करें',
    language: 'भाषा',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    notifications: 'सूचनाएं',
    applicationTimeline: 'आवेदन समयरेखा',
    viewDetails: 'विवरण देखें',
    applyForScheme: 'योजना के लिए आवेदन करें',
    checkEligibility: 'पात्रता जांचें',
    documentsRequired: 'आवश्यक दस्तावेज',
    benefits: 'लाभ',
    days: 'दिन',
    allSchemes: 'सभी योजनाएं',
    searchSchemes: 'योजनाएं खोजें...',
    filterByCategory: 'श्रेणी के अनुसार फ़िल्टर करें',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    myApplications: 'என் விண்ணப்பங்கள்',
    schemes: 'திட்டங்கள்',
    transparency: 'வெளிப்படைத்தன்மை',
    help: 'உதவி',
    welcome: 'குடிமக்கள் போர்ட்டலுக்கு வரவேற்கிறோம்',
    welcomeDesc: 'மானியங்களுக்கு விண்ணப்பிக்கவும், உங்கள் விண்ணப்பங்களைக் கண்காணிக்கவும்',
    applyNow: 'இப்போது விண்ணப்பிக்கவும்',
    trackStatus: 'நிலையைக் கண்காணிக்கவும்',
    viewAll: 'அனைத்தையும் பார்க்க',
    submitted: 'சமர்ப்பிக்கப்பட்டது',
    fraudCheck: 'மோசடி சோதனை',
    approved: 'அங்கீகரிக்கப்பட்டது',
    disbursed: 'வழங்கப்பட்டது',
    pending: 'நிலுவையில்',
    rejected: 'நிராகரிக்கப்பட்டது',
    inProgress: 'செயல்பாட்டில்',
    completed: 'முடிந்தது',
    expectedDate: 'எதிர்பார்க்கப்படும் தேதி',
    amount: 'தொகை',
    status: 'நிலை',
    schemeName: 'திட்டத்தின் பெயர்',
    education: 'கல்வி',
    finance: 'நிதி',
    agriculture: 'விவசாயம்',
    health: 'சுகாதாரம்',
    housing: 'வீட்டுவசதி',
    employment: 'வேலைவாய்ப்பு',
    eligibilityCheck: 'தகுதியை சரிபார்க்கவும்',
    chatWithUs: 'எங்களுடன் அரட்டை',
    voiceAssistant: 'குரல் உதவியாளர்',
    speakNow: 'இப்போது பேசுங்கள்',
    listening: 'கேட்கிறேன்...',
    recommendations: 'உங்களுக்கு பரிந்துரைக்கப்பட்டவை',
    totalApplications: 'மொத்த விண்ணப்பங்கள்',
    approvedApplications: 'அங்கீகரிக்கப்பட்டது',
    pendingApplications: 'நிலுவையில்',
    disbursedAmount: 'வழங்கப்பட்ட தொகை',
    transparencyMetrics: 'வெளிப்படைத்தன்மை அளவீடுகள்',
    processingTime: 'சராசரி செயலாக்க நேரம்',
    successRate: 'வெற்றி விகிதம்',
    totalDisbursed: 'மொத்தம் வழங்கப்பட்டது',
    askQuestion: 'ஒரு கேள்வி கேளுங்கள்...',
    send: 'அனுப்பு',
    close: 'மூடு',
    language: 'மொழி',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    notifications: 'அறிவிப்புகள்',
    applicationTimeline: 'விண்ணப்ப காலவரிசை',
    viewDetails: 'விவரங்களைக் காண்க',
    applyForScheme: 'திட்டத்திற்கு விண்ணப்பிக்கவும்',
    checkEligibility: 'தகுதியை சரிபார்க்கவும்',
    documentsRequired: 'தேவையான ஆவணங்கள்',
    benefits: 'நன்மைகள்',
    days: 'நாட்கள்',
    allSchemes: 'அனைத்து திட்டங்கள்',
    searchSchemes: 'திட்டங்களைத் தேடுங்கள்...',
    filterByCategory: 'வகையின் அடிப்படையில் வடிகட்டு',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    myApplications: 'నా దరఖాస్తులు',
    schemes: 'పథకాలు',
    transparency: 'పారదర్శకత',
    help: 'సహాయం',
    welcome: 'పౌర పోర్టల్‌కు స్వాగతం',
    welcomeDesc: 'సబ్సిడీల కోసం దరఖాస్తు చేయండి మరియు మీ దరఖాస్తులను ట్రాక్ చేయండి',
    applyNow: 'ఇప్పుడు దరఖాస్తు చేయండి',
    trackStatus: 'స్థితిని ట్రాక్ చేయండి',
    viewAll: 'అన్నీ చూడండి',
    submitted: 'సమర్పించబడింది',
    fraudCheck: 'మోసం తనిఖీ',
    approved: 'ఆమోదించబడింది',
    disbursed: 'పంపిణీ చేయబడింది',
    pending: 'పెండింగ్‌లో',
    rejected: 'తిరస్కరించబడింది',
    inProgress: 'ప్రక్రియలో',
    completed: 'పూర్తయింది',
    expectedDate: 'అంచనా తేదీ',
    amount: 'మొత్తం',
    status: 'స్థితి',
    schemeName: 'పథకం పేరు',
    education: 'విద్య',
    finance: 'ఆర్థిక',
    agriculture: 'వ్యవసాయం',
    health: 'ఆరోగ్యం',
    housing: 'గృహ',
    employment: 'ఉపాధి',
    eligibilityCheck: 'అర్హతను తనిఖీ చేయండి',
    chatWithUs: 'మాతో చాట్ చేయండి',
    voiceAssistant: 'వాయిస్ అసిస్టెంట్',
    speakNow: 'ఇప్పుడు మాట్లాడండి',
    listening: 'వింటోంది...',
    recommendations: 'మీ కోసం సిఫార్సులు',
    totalApplications: 'మొత్తం దరఖాస్తులు',
    approvedApplications: 'ఆమోదించబడింది',
    pendingApplications: 'పెండింగ్‌లో',
    disbursedAmount: 'పంపిణీ మొత్తం',
    transparencyMetrics: 'పారదర్శకత మెట్రిక్స్',
    processingTime: 'సగటు ప్రాసెసింగ్ సమయం',
    successRate: 'విజయ రేటు',
    totalDisbursed: 'మొత్తం పంపిణీ',
    askQuestion: 'ప్రశ్న అడగండి...',
    send: 'పంపు',
    close: 'మూసివేయి',
    language: 'భాష',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    notifications: 'నోటిఫికేషన్లు',
    applicationTimeline: 'దరఖాస్తు టైమ్‌లైన్',
    viewDetails: 'వివరాలు చూడండి',
    applyForScheme: 'పథకానికి దరఖాస్తు చేయండి',
    checkEligibility: 'అర్హతను తనిఖీ చేయండి',
    documentsRequired: 'అవసరమైన పత్రాలు',
    benefits: 'ప్రయోజనాలు',
    days: 'రోజులు',
    allSchemes: 'అన్ని పథకాలు',
    searchSchemes: 'పథకాలను వెతకండి...',
    filterByCategory: 'వర్గం ద్వారా ఫిల్టర్ చేయండి',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    myApplications: 'আমার আবেদন',
    schemes: 'স্কিম',
    transparency: 'স্বচ্ছতা',
    help: 'সাহায্য',
    welcome: 'নাগরিক পোর্টালে স্বাগতম',
    welcomeDesc: 'ভর্তুকির জন্য আবেদন করুন এবং আপনার আবেদনগুলি ট্র্যাক করুন',
    applyNow: 'এখনই আবেদন করুন',
    trackStatus: 'স্ট্যাটাস ট্র্যাক করুন',
    viewAll: 'সব দেখুন',
    submitted: 'জমা দেওয়া হয়েছে',
    fraudCheck: 'জালিয়াতি পরীক্ষা',
    approved: 'অনুমোদিত',
    disbursed: 'বিতরণ করা হয়েছে',
    pending: 'মুলতুবি',
    rejected: 'প্রত্যাখ্যাত',
    inProgress: 'প্রগতিতে',
    completed: 'সম্পূর্ণ',
    expectedDate: 'প্রত্যাশিত তারিখ',
    amount: 'পরিমাণ',
    status: 'স্ট্যাটাস',
    schemeName: 'স্কিমের নাম',
    education: 'শিক্ষা',
    finance: 'অর্থ',
    agriculture: 'কৃষি',
    health: 'স্বাস্থ্য',
    housing: 'আবাসন',
    employment: 'কর্মসংস্থান',
    eligibilityCheck: 'যোগ্যতা পরীক্ষা করুন',
    chatWithUs: 'আমাদের সাথে চ্যাট করুন',
    voiceAssistant: 'ভয়েস সহকারী',
    speakNow: 'এখন বলুন',
    listening: 'শুনছি...',
    recommendations: 'আপনার জন্য সুপারিশ',
    totalApplications: 'মোট আবেদন',
    approvedApplications: 'অনুমোদিত',
    pendingApplications: 'মুলতুবি',
    disbursedAmount: 'বিতরণ পরিমাণ',
    transparencyMetrics: 'স্বচ্ছতা মেট্রিক্স',
    processingTime: 'গড় প্রক্রিয়াকরণ সময়',
    successRate: 'সাফল্যের হার',
    totalDisbursed: 'মোট বিতরণ',
    askQuestion: 'একটি প্রশ্ন জিজ্ঞাসা করুন...',
    send: 'পাঠান',
    close: 'বন্ধ',
    language: 'ভাষা',
    profile: 'প্রোফাইল',
    logout: 'লগ আউট',
    notifications: 'বিজ্ঞপ্তি',
    applicationTimeline: 'আবেদনের সময়রেখা',
    viewDetails: 'বিস্তারিত দেখুন',
    applyForScheme: 'স্কিমের জন্য আবেদন করুন',
    checkEligibility: 'যোগ্যতা পরীক্ষা করুন',
    documentsRequired: 'প্রয়োজনীয় নথি',
    benefits: 'সুবিধা',
    days: 'দিন',
    allSchemes: 'সব স্কিম',
    searchSchemes: 'স্কিম খুঁজুন...',
    filterByCategory: 'বিভাগ অনুসারে ফিল্টার করুন',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    myApplications: 'माझे अर्ज',
    schemes: 'योजना',
    transparency: 'पारदर्शकता',
    help: 'मदत',
    welcome: 'नागरिक पोर्टलवर स्वागत आहे',
    welcomeDesc: 'अनुदानासाठी अर्ज करा आणि तुमच्या अर्जांचा मागोवा घ्या',
    applyNow: 'आता अर्ज करा',
    trackStatus: 'स्थिती ट्रॅक करा',
    viewAll: 'सर्व पहा',
    submitted: 'सबमिट केले',
    fraudCheck: 'फसवणूक तपासणी',
    approved: 'मंजूर',
    disbursed: 'वितरित',
    pending: 'प्रलंबित',
    rejected: 'नाकारले',
    inProgress: 'प्रगतीत',
    completed: 'पूर्ण',
    expectedDate: 'अपेक्षित तारीख',
    amount: 'रक्कम',
    status: 'स्थिती',
    schemeName: 'योजनेचे नाव',
    education: 'शिक्षण',
    finance: 'वित्त',
    agriculture: 'शेती',
    health: 'आरोग्य',
    housing: 'गृहनिर्माण',
    employment: 'रोजगार',
    eligibilityCheck: 'पात्रता तपासा',
    chatWithUs: 'आमच्याशी चॅट करा',
    voiceAssistant: 'व्हॉइस असिस्टंट',
    speakNow: 'आता बोला',
    listening: 'ऐकत आहे...',
    recommendations: 'तुमच्यासाठी शिफारस केलेले',
    totalApplications: 'एकूण अर्ज',
    approvedApplications: 'मंजूर',
    pendingApplications: 'प्रलंबित',
    disbursedAmount: 'वितरित रक्कम',
    transparencyMetrics: 'पारदर्शकता मेट्रिक्स',
    processingTime: 'सरासरी प्रक्रिया वेळ',
    successRate: 'यश दर',
    totalDisbursed: 'एकूण वितरित',
    askQuestion: 'प्रश्न विचारा...',
    send: 'पाठवा',
    close: 'बंद करा',
    language: 'भाषा',
    profile: 'प्रोफाइल',
    logout: 'लॉग आउट',
    notifications: 'सूचना',
    applicationTimeline: 'अर्ज टाइमलाइन',
    viewDetails: 'तपशील पहा',
    applyForScheme: 'योजनेसाठी अर्ज करा',
    checkEligibility: 'पात्रता तपासा',
    documentsRequired: 'आवश्यक कागदपत्रे',
    benefits: 'फायदे',
    days: 'दिवस',
    allSchemes: 'सर्व योजना',
    searchSchemes: 'योजना शोधा...',
    filterByCategory: 'श्रेणीनुसार फिल्टर करा',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    myApplications: 'મારી અરજીઓ',
    schemes: 'યોજનાઓ',
    transparency: 'પારદર્શિતા',
    help: 'મદદ',
    welcome: 'નાગરિક પોર્ટલમાં આપનું સ્વાગત છે',
    welcomeDesc: 'સબસિડી માટે અરજી કરો અને તમારી અરજીઓને ટ્રેક કરો',
    applyNow: 'હમણાં અરજી કરો',
    trackStatus: 'સ્ટેટસ ટ્રેક કરો',
    viewAll: 'બધા જુઓ',
    submitted: 'સબમિટ કર્યું',
    fraudCheck: 'છેતરપિંડી તપાસ',
    approved: 'મંજૂર',
    disbursed: 'વિતરિત',
    pending: 'પેન્ડિંગ',
    rejected: 'નકાર્યું',
    inProgress: 'પ્રગતિમાં',
    completed: 'પૂર્ણ',
    expectedDate: 'અપેક્ષિત તારીખ',
    amount: 'રકમ',
    status: 'સ્ટેટસ',
    schemeName: 'યોજનાનું નામ',
    education: 'શિક્ષણ',
    finance: 'નાણા',
    agriculture: 'કૃષિ',
    health: 'આરોગ્ય',
    housing: 'આવાસ',
    employment: 'રોજગાર',
    eligibilityCheck: 'પાત્રતા તપાસો',
    chatWithUs: 'અમારી સાથે ચેટ કરો',
    voiceAssistant: 'વોઈસ આસિસ્ટન્ટ',
    speakNow: 'હવે બોલો',
    listening: 'સાંભળું છું...',
    recommendations: 'તમારા માટે ભલામણ',
    totalApplications: 'કુલ અરજીઓ',
    approvedApplications: 'મંજૂર',
    pendingApplications: 'પેન્ડિંગ',
    disbursedAmount: 'વિતરિત રકમ',
    transparencyMetrics: 'પારદર્શિતા મેટ્રિક્સ',
    processingTime: 'સરેરાશ પ્રોસેસિંગ સમય',
    successRate: 'સફળતા દર',
    totalDisbursed: 'કુલ વિતરિત',
    askQuestion: 'પ્રશ્ન પૂછો...',
    send: 'મોકલો',
    close: 'બંધ કરો',
    language: 'ભાષા',
    profile: 'પ્રોફાઇલ',
    logout: 'લોગ આઉટ',
    notifications: 'સૂચનાઓ',
    applicationTimeline: 'અરજી ટાઇમલાઇન',
    viewDetails: 'વિગતો જુઓ',
    applyForScheme: 'યોજના માટે અરજી કરો',
    checkEligibility: 'પાત્રતા તપાસો',
    documentsRequired: 'જરૂરી દસ્તાવેજો',
    benefits: 'લાભો',
    days: 'દિવસ',
    allSchemes: 'બધી યોજનાઓ',
    searchSchemes: 'યોજનાઓ શોધો...',
    filterByCategory: 'શ્રેણી દ્વારા ફિલ્ટર કરો',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    myApplications: 'ನನ್ನ ಅರ್ಜಿಗಳು',
    schemes: 'ಯೋಜನೆಗಳು',
    transparency: 'ಪಾರದರ್ಶಕತೆ',
    help: 'ಸಹಾಯ',
    welcome: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್‌ಗೆ ಸ್ವಾಗತ',
    welcomeDesc: 'ಸಬ್ಸಿಡಿಗಳಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಅರ್ಜಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    applyNow: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    trackStatus: 'ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    viewAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    submitted: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    fraudCheck: 'ವಂಚನೆ ತಪಾಸಣೆ',
    approved: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    disbursed: 'ವಿತರಿಸಲಾಗಿದೆ',
    pending: 'ಬಾಕಿ',
    rejected: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    expectedDate: 'ನಿರೀಕ್ಷಿತ ದಿನಾಂಕ',
    amount: 'ಮೊತ್ತ',
    status: 'ಸ್ಥಿತಿ',
    schemeName: 'ಯೋಜನೆ ಹೆಸರು',
    education: 'ಶಿಕ್ಷಣ',
    finance: 'ಹಣಕಾಸು',
    agriculture: 'ಕೃಷಿ',
    health: 'ಆರೋಗ್ಯ',
    housing: 'ವಸತಿ',
    employment: 'ಉದ್ಯೋಗ',
    eligibilityCheck: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    chatWithUs: 'ನಮ್ಮೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
    voiceAssistant: 'ಧ್ವನಿ ಸಹಾಯಕ',
    speakNow: 'ಈಗ ಮಾತನಾಡಿ',
    listening: 'ಕೇಳುತ್ತಿದೆ...',
    recommendations: 'ನಿಮಗಾಗಿ ಶಿಫಾರಸುಗಳು',
    totalApplications: 'ಒಟ್ಟು ಅರ್ಜಿಗಳು',
    approvedApplications: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    pendingApplications: 'ಬಾಕಿ',
    disbursedAmount: 'ವಿತರಿಸಿದ ಮೊತ್ತ',
    transparencyMetrics: 'ಪಾರದರ್ಶಕತೆ ಮೆಟ್ರಿಕ್ಸ್',
    processingTime: 'ಸರಾಸರಿ ಪ್ರಕ್ರಿಯೆ ಸಮಯ',
    successRate: 'ಯಶಸ್ಸಿನ ದರ',
    totalDisbursed: 'ಒಟ್ಟು ವಿತರಿಸಲಾಗಿದೆ',
    askQuestion: 'ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    send: 'ಕಳುಹಿಸಿ',
    close: 'ಮುಚ್ಚು',
    language: 'ಭಾಷೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    applicationTimeline: 'ಅರ್ಜಿ ಟೈಮ್‌ಲೈನ್',
    viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    applyForScheme: 'ಯೋಜನೆಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    checkEligibility: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    documentsRequired: 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
    benefits: 'ಪ್ರಯೋಜನಗಳು',
    days: 'ದಿನಗಳು',
    allSchemes: 'ಎಲ್ಲಾ ಯೋಜನೆಗಳು',
    searchSchemes: 'ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...',
    filterByCategory: 'ವರ್ಗದ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ',
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    myApplications: 'എന്റെ അപേക്ഷകൾ',
    schemes: 'പദ്ധതികൾ',
    transparency: 'സുതാര്യത',
    help: 'സഹായം',
    welcome: 'സിറ്റിസൺ പോർട്ടലിലേക്ക് സ്വാഗതം',
    welcomeDesc: 'സബ്‌സിഡികൾക്ക് അപേക്ഷിക്കുകയും നിങ്ങളുടെ അപേക്ഷകൾ ട്രാക്ക് ചെയ്യുകയും ചെയ്യുക',
    applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    trackStatus: 'സ്ഥിതി ട്രാക്ക് ചെയ്യുക',
    viewAll: 'എല്ലാം കാണുക',
    submitted: 'സമർപ്പിച്ചു',
    fraudCheck: 'വഞ്ചനാ പരിശോധന',
    approved: 'അംഗീകരിച്ചു',
    disbursed: 'വിതരണം ചെയ്തു',
    pending: 'തീർപ്പാക്കാത്ത',
    rejected: 'നിരസിച്ചു',
    inProgress: 'പുരോഗതിയിൽ',
    completed: 'പൂർത്തിയായി',
    expectedDate: 'പ്രതീക്ഷിക്കുന്ന തീയതി',
    amount: 'തുക',
    status: 'സ്ഥിതി',
    schemeName: 'പദ്ധതിയുടെ പേര്',
    education: 'വിദ്യാഭ്യാസം',
    finance: 'ധനകാര്യം',
    agriculture: 'കൃഷി',
    health: 'ആരോഗ്യം',
    housing: 'പാർപ്പിടം',
    employment: 'തൊഴിൽ',
    eligibilityCheck: 'യോഗ്യത പരിശോധിക്കുക',
    chatWithUs: 'ഞങ്ങളുമായി ചാറ്റ് ചെയ്യുക',
    voiceAssistant: 'വോയ്‌സ് അസിസ്റ്റന്റ്',
    speakNow: 'ഇപ്പോൾ സംസാരിക്കുക',
    listening: 'കേൾക്കുന്നു...',
    recommendations: 'നിങ്ങൾക്കുള്ള ശുപാർശകൾ',
    totalApplications: 'മൊത്തം അപേക്ഷകൾ',
    approvedApplications: 'അംഗീകരിച്ചു',
    pendingApplications: 'തീർപ്പാക്കാത്ത',
    disbursedAmount: 'വിതരണം ചെയ്ത തുക',
    transparencyMetrics: 'സുതാര്യത മെട്രിക്സ്',
    processingTime: 'ശരാശരി പ്രോസസ്സിംഗ് സമയം',
    successRate: 'വിജയ നിരക്ക്',
    totalDisbursed: 'മൊത്തം വിതരണം ചെയ്തു',
    askQuestion: 'ഒരു ചോദ്യം ചോദിക്കുക...',
    send: 'അയയ്ക്കുക',
    close: 'അടയ്ക്കുക',
    language: 'ഭാഷ',
    profile: 'പ്രൊഫൈൽ',
    logout: 'ലോഗ് ഔട്ട്',
    notifications: 'അറിയിപ്പുകൾ',
    applicationTimeline: 'അപേക്ഷ ടൈംലൈൻ',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    applyForScheme: 'പദ്ധതിക്ക് അപേക്ഷിക്കുക',
    checkEligibility: 'യോഗ്യത പരിശോധിക്കുക',
    documentsRequired: 'ആവശ്യമായ രേഖകൾ',
    benefits: 'ആനുകൂല്യങ്ങൾ',
    days: 'ദിവസങ്ങൾ',
    allSchemes: 'എല്ലാ പദ്ധതികളും',
    searchSchemes: 'പദ്ധതികൾ തിരയുക...',
    filterByCategory: 'വിഭാഗം അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    myApplications: 'ਮੇਰੀਆਂ ਅਰਜ਼ੀਆਂ',
    schemes: 'ਸਕੀਮਾਂ',
    transparency: 'ਪਾਰਦਰਸ਼ਤਾ',
    help: 'ਮਦਦ',
    welcome: 'ਨਾਗਰਿਕ ਪੋਰਟਲ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
    welcomeDesc: 'ਸਬਸਿਡੀਆਂ ਲਈ ਅਰਜ਼ੀ ਦਿਓ ਅਤੇ ਆਪਣੀਆਂ ਅਰਜ਼ੀਆਂ ਨੂੰ ਟਰੈਕ ਕਰੋ',
    applyNow: 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ',
    trackStatus: 'ਸਥਿਤੀ ਟਰੈਕ ਕਰੋ',
    viewAll: 'ਸਭ ਦੇਖੋ',
    submitted: 'ਜਮ੍ਹਾਂ ਕੀਤਾ',
    fraudCheck: 'ਧੋਖਾਧੜੀ ਜਾਂਚ',
    approved: 'ਮਨਜ਼ੂਰ',
    disbursed: 'ਵੰਡਿਆ ਗਿਆ',
    pending: 'ਬਕਾਇਆ',
    rejected: 'ਰੱਦ',
    inProgress: 'ਪ੍ਰਗਤੀ ਵਿੱਚ',
    completed: 'ਪੂਰਾ',
    expectedDate: 'ਸੰਭਾਵਿਤ ਤਾਰੀਖ',
    amount: 'ਰਕਮ',
    status: 'ਸਥਿਤੀ',
    schemeName: 'ਸਕੀਮ ਦਾ ਨਾਮ',
    education: 'ਸਿੱਖਿਆ',
    finance: 'ਵਿੱਤ',
    agriculture: 'ਖੇਤੀਬਾੜੀ',
    health: 'ਸਿਹਤ',
    housing: 'ਰਿਹਾਇਸ਼',
    employment: 'ਰੁਜ਼ਗਾਰ',
    eligibilityCheck: 'ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    chatWithUs: 'ਸਾਡੇ ਨਾਲ ਗੱਲ ਕਰੋ',
    voiceAssistant: 'ਵੌਇਸ ਸਹਾਇਕ',
    speakNow: 'ਹੁਣ ਬੋਲੋ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ...',
    recommendations: 'ਤੁਹਾਡੇ ਲਈ ਸਿਫਾਰਸ਼ਾਂ',
    totalApplications: 'ਕੁੱਲ ਅਰਜ਼ੀਆਂ',
    approvedApplications: 'ਮਨਜ਼ੂਰ',
    pendingApplications: 'ਬਕਾਇਆ',
    disbursedAmount: 'ਵੰਡੀ ਗਈ ਰਕਮ',
    transparencyMetrics: 'ਪਾਰਦਰਸ਼ਤਾ ਮੈਟ੍ਰਿਕਸ',
    processingTime: 'ਔਸਤ ਪ੍ਰੋਸੈਸਿੰਗ ਸਮਾਂ',
    successRate: 'ਸਫਲਤਾ ਦਰ',
    totalDisbursed: 'ਕੁੱਲ ਵੰਡਿਆ ਗਿਆ',
    askQuestion: 'ਸਵਾਲ ਪੁੱਛੋ...',
    send: 'ਭੇਜੋ',
    close: 'ਬੰਦ ਕਰੋ',
    language: 'ਭਾਸ਼ਾ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    logout: 'ਲੌਗ ਆਊਟ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    applicationTimeline: 'ਅਰਜ਼ੀ ਟਾਈਮਲਾਈਨ',
    viewDetails: 'ਵੇਰਵੇ ਦੇਖੋ',
    applyForScheme: 'ਸਕੀਮ ਲਈ ਅਰਜ਼ੀ ਦਿਓ',
    checkEligibility: 'ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ',
    documentsRequired: 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
    benefits: 'ਲਾਭ',
    days: 'ਦਿਨ',
    allSchemes: 'ਸਾਰੀਆਂ ਸਕੀਮਾਂ',
    searchSchemes: 'ਸਕੀਮਾਂ ਖੋਜੋ...',
    filterByCategory: 'ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਫਿਲਟਰ ਕਰੋ',
  },
  es: {
    dashboard: 'Panel',
    myApplications: 'Mis Solicitudes',
    schemes: 'Programas',
    transparency: 'Transparencia',
    help: 'Ayuda',
    welcome: 'Bienvenido al Portal Ciudadano',
    welcomeDesc: 'Solicite subsidios y haga seguimiento de sus solicitudes',
    applyNow: 'Solicitar Ahora',
    trackStatus: 'Seguir Estado',
    viewAll: 'Ver Todo',
    submitted: 'Enviado',
    fraudCheck: 'Verificación de Fraude',
    approved: 'Aprobado',
    disbursed: 'Desembolsado',
    pending: 'Pendiente',
    rejected: 'Rechazado',
    inProgress: 'En Progreso',
    completed: 'Completado',
    expectedDate: 'Fecha Esperada',
    amount: 'Monto',
    status: 'Estado',
    schemeName: 'Nombre del Programa',
    education: 'Educación',
    finance: 'Finanzas',
    agriculture: 'Agricultura',
    health: 'Salud',
    housing: 'Vivienda',
    employment: 'Empleo',
    eligibilityCheck: 'Verificar Elegibilidad',
    chatWithUs: 'Chatea con Nosotros',
    voiceAssistant: 'Asistente de Voz',
    speakNow: 'Hable Ahora',
    listening: 'Escuchando...',
    recommendations: 'Recomendado para Usted',
    totalApplications: 'Total de Solicitudes',
    approvedApplications: 'Aprobadas',
    pendingApplications: 'Pendientes',
    disbursedAmount: 'Monto Desembolsado',
    transparencyMetrics: 'Métricas de Transparencia',
    processingTime: 'Tiempo Promedio de Procesamiento',
    successRate: 'Tasa de Éxito',
    totalDisbursed: 'Total Desembolsado',
    askQuestion: 'Haga una pregunta...',
    send: 'Enviar',
    close: 'Cerrar',
    language: 'Idioma',
    profile: 'Perfil',
    logout: 'Cerrar Sesión',
    notifications: 'Notificaciones',
    applicationTimeline: 'Línea de Tiempo de Solicitud',
    viewDetails: 'Ver Detalles',
    applyForScheme: 'Solicitar Programa',
    checkEligibility: 'Verificar Elegibilidad',
    documentsRequired: 'Documentos Requeridos',
    benefits: 'Beneficios',
    days: 'días',
    allSchemes: 'Todos los Programas',
    searchSchemes: 'Buscar programas...',
    filterByCategory: 'Filtrar por categoría',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    myApplications: 'Mes Demandes',
    schemes: 'Programmes',
    transparency: 'Transparence',
    help: 'Aide',
    welcome: 'Bienvenue sur le Portail Citoyen',
    welcomeDesc: 'Faites une demande de subvention et suivez vos demandes',
    applyNow: 'Postuler Maintenant',
    trackStatus: 'Suivre le Statut',
    viewAll: 'Voir Tout',
    submitted: 'Soumis',
    fraudCheck: 'Vérification de Fraude',
    approved: 'Approuvé',
    disbursed: 'Versé',
    pending: 'En Attente',
    rejected: 'Rejeté',
    inProgress: 'En Cours',
    completed: 'Terminé',
    expectedDate: 'Date Prévue',
    amount: 'Montant',
    status: 'Statut',
    schemeName: 'Nom du Programme',
    education: 'Éducation',
    finance: 'Finance',
    agriculture: 'Agriculture',
    health: 'Santé',
    housing: 'Logement',
    employment: 'Emploi',
    eligibilityCheck: 'Vérifier Éligibilité',
    chatWithUs: 'Discutez avec Nous',
    voiceAssistant: 'Assistant Vocal',
    speakNow: 'Parlez Maintenant',
    listening: 'Écoute...',
    recommendations: 'Recommandé pour Vous',
    totalApplications: 'Total des Demandes',
    approvedApplications: 'Approuvées',
    pendingApplications: 'En Attente',
    disbursedAmount: 'Montant Versé',
    transparencyMetrics: 'Métriques de Transparence',
    processingTime: 'Temps de Traitement Moyen',
    successRate: 'Taux de Réussite',
    totalDisbursed: 'Total Versé',
    askQuestion: 'Posez une question...',
    send: 'Envoyer',
    close: 'Fermer',
    language: 'Langue',
    profile: 'Profil',
    logout: 'Déconnexion',
    notifications: 'Notifications',
    applicationTimeline: 'Chronologie de la Demande',
    viewDetails: 'Voir les Détails',
    applyForScheme: 'Postuler au Programme',
    checkEligibility: 'Vérifier Éligibilité',
    documentsRequired: 'Documents Requis',
    benefits: 'Avantages',
    days: 'jours',
    allSchemes: 'Tous les Programmes',
    searchSchemes: 'Rechercher des programmes...',
    filterByCategory: 'Filtrer par catégorie',
  },
  de: {
    dashboard: 'Dashboard',
    myApplications: 'Meine Anträge',
    schemes: 'Programme',
    transparency: 'Transparenz',
    help: 'Hilfe',
    welcome: 'Willkommen im Bürgerportal',
    welcomeDesc: 'Beantragen Sie Zuschüsse und verfolgen Sie Ihre Anträge',
    applyNow: 'Jetzt Beantragen',
    trackStatus: 'Status Verfolgen',
    viewAll: 'Alle Anzeigen',
    submitted: 'Eingereicht',
    fraudCheck: 'Betrugsprüfung',
    approved: 'Genehmigt',
    disbursed: 'Ausgezahlt',
    pending: 'Ausstehend',
    rejected: 'Abgelehnt',
    inProgress: 'In Bearbeitung',
    completed: 'Abgeschlossen',
    expectedDate: 'Erwartetes Datum',
    amount: 'Betrag',
    status: 'Status',
    schemeName: 'Programmname',
    education: 'Bildung',
    finance: 'Finanzen',
    agriculture: 'Landwirtschaft',
    health: 'Gesundheit',
    housing: 'Wohnen',
    employment: 'Beschäftigung',
    eligibilityCheck: 'Berechtigung Prüfen',
    chatWithUs: 'Mit uns Chatten',
    voiceAssistant: 'Sprachassistent',
    speakNow: 'Jetzt Sprechen',
    listening: 'Höre zu...',
    recommendations: 'Für Sie Empfohlen',
    totalApplications: 'Gesamtanträge',
    approvedApplications: 'Genehmigt',
    pendingApplications: 'Ausstehend',
    disbursedAmount: 'Ausgezahlter Betrag',
    transparencyMetrics: 'Transparenz-Metriken',
    processingTime: 'Durchschn. Bearbeitungszeit',
    successRate: 'Erfolgsquote',
    totalDisbursed: 'Gesamt Ausgezahlt',
    askQuestion: 'Stellen Sie eine Frage...',
    send: 'Senden',
    close: 'Schließen',
    language: 'Sprache',
    profile: 'Profil',
    logout: 'Abmelden',
    notifications: 'Benachrichtigungen',
    applicationTimeline: 'Antragszeitachse',
    viewDetails: 'Details Anzeigen',
    applyForScheme: 'Für Programm Bewerben',
    checkEligibility: 'Berechtigung Prüfen',
    documentsRequired: 'Erforderliche Dokumente',
    benefits: 'Vorteile',
    days: 'Tage',
    allSchemes: 'Alle Programme',
    searchSchemes: 'Programme suchen...',
    filterByCategory: 'Nach Kategorie filtern',
  },
  ar: {
    dashboard: 'لوحة القيادة',
    myApplications: 'طلباتي',
    schemes: 'البرامج',
    transparency: 'الشفافية',
    help: 'مساعدة',
    welcome: 'مرحباً بكم في بوابة المواطن',
    welcomeDesc: 'تقدم بطلب للحصول على الدعم وتتبع طلباتك',
    applyNow: 'تقدم الآن',
    trackStatus: 'تتبع الحالة',
    viewAll: 'عرض الكل',
    submitted: 'تم التقديم',
    fraudCheck: 'فحص الاحتيال',
    approved: 'موافق عليه',
    disbursed: 'تم الصرف',
    pending: 'قيد الانتظار',
    rejected: 'مرفوض',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    expectedDate: 'التاريخ المتوقع',
    amount: 'المبلغ',
    status: 'الحالة',
    schemeName: 'اسم البرنامج',
    education: 'التعليم',
    finance: 'المالية',
    agriculture: 'الزراعة',
    health: 'الصحة',
    housing: 'الإسكان',
    employment: 'التوظيف',
    eligibilityCheck: 'التحقق من الأهلية',
    chatWithUs: 'تحدث معنا',
    voiceAssistant: 'المساعد الصوتي',
    speakNow: 'تحدث الآن',
    listening: 'جاري الاستماع...',
    recommendations: 'موصى به لك',
    totalApplications: 'إجمالي الطلبات',
    approvedApplications: 'موافق عليه',
    pendingApplications: 'قيد الانتظار',
    disbursedAmount: 'المبلغ المصروف',
    transparencyMetrics: 'مقاييس الشفافية',
    processingTime: 'متوسط وقت المعالجة',
    successRate: 'معدل النجاح',
    totalDisbursed: 'إجمالي المصروفات',
    askQuestion: 'اطرح سؤالاً...',
    send: 'إرسال',
    close: 'إغلاق',
    language: 'اللغة',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    notifications: 'الإشعارات',
    applicationTimeline: 'الجدول الزمني للطلب',
    viewDetails: 'عرض التفاصيل',
    applyForScheme: 'التقدم للبرنامج',
    checkEligibility: 'التحقق من الأهلية',
    documentsRequired: 'المستندات المطلوبة',
    benefits: 'الفوائد',
    days: 'أيام',
    allSchemes: 'جميع البرامج',
    searchSchemes: 'البحث عن البرامج...',
    filterByCategory: 'تصفية حسب الفئة',
  },
}

const languages: { code: Language; name: string; nativeName: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
]

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
